name: eskema
description: Eskema is a small, composable runtime validation library for Dart. It helps you validate dynamic values (JSON, Maps, Lists, primitives) with readable validators and clear error messages.

version: 1.0.0
homepage: https://github.com/nombrekeff/eskema

environment:
  sdk: '^3.0.0'

dependencies:
  collection: ^1.19.1

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
  